<<<<<<< HEAD
resolver: lts-9.14

nix:
  enable: true
  packages:
    - ncurses
    - binutils
    - zlib
=======
resolver: lts-9.15

extra-deps: []

nix:
  enable: true
  pure: true
  packages:
    - ncurses
    - binutils
    - zlib
    - gcc
>>>>>>> git broke a bit
